### ISSUE TITLE
Narrowing conversion error on Windows.

### ISSUE THREAD

**Issue by phuongtran7** [morganstanley/binlog#32] opened 2020-03-04 17:28 UTC
Hello,

I'm trying out the library on Windows and it seems that I couldn't get it to work properly. Every time I try to compile the `helloworld` example, I got the `error C2397: conversion from 'long' to 'uint64_t' requires a narrowing conversion` at the `BINLOG_INFO("Hello {}!", "World");` line.

However, when I compile the same code with WSL (GCC 8.3.0) everything works as expected, no warning at all. I also was able to build the `helloworld` example in the CMake generated project, and it ran just fine with the same VS.

I'm using Visual Studio 2019 on Windows 10.

I might be missing something obvious but I couldn't figure it out. Thank you so much for your time and help.

**Comment by erenon** [comment] 2020-03-04 18:42
Thanks for your feedback! GitHub provides `Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314` in their CI, and binlog compiles there without error ([example](https://github.com/Morgan-Stanley/binlog/runs/475525555?check_suite_focus=true)). 
What's your exact compiler version?

Do you have a longer compiler error message or backtrace? Binlog itself does not use `long` at all (because of the platform differences like this), so I can't tell where the error is coming from.

**Comment by phuongtran7** [comment] 2020-03-04 19:07
Thank you for your prompt response. I'm using the latest Visual Studio (Version 16.4.5) and the same MSVC version as the CI (14.24.28314). The attached file is detailed build log I got from Visual Studio.

[Test_Binlog.log](https://github.com/Morgan-Stanley/binlog/files/4289212/Test_Binlog.log)

Thank you so much for your time and help.

**Comment by erenon** [comment] 2020-03-04 19:17
Please also attach the full `D:\Projects\Test_Binlog\Test_Binlog\Test_Binlog.cpp` file.

**Comment by phuongtran7** [comment] 2020-03-04 19:21
GitHub does not allow to attach `.cpp` file so I renamed it to `.txt` here. Also it's just a simple `helloworld` just like in your instruction:

```
#include <binlog/binlog.hpp>
#include <fstream>
#include <iostream>

int main()
{
    BINLOG_INFO("Hello {}!", "World");

    std::ofstream logfile("hello.blog", std::ofstream::out | std::ofstream::binary);
    binlog::consume(logfile);

    if (!logfile)
    {
        std::cerr << "Failed to write hello.blog\n";
        return 1;
    }

    std::cout << "Binary log written to hello.blog\n";
    return 0;
}
```
[Test_Binlog.txt](https://github.com/Morgan-Stanley/binlog/files/4289271/Test_Binlog.txt)

Thank you so much for your time and help.

**Comment by phuongtran7** [comment] 2020-03-04 22:40
I'm so sorry for the late reply. I turned on the `Preprocess to a File` and it was able to output the `.i` file just fine. The attached log is the output of that.

Also, after looking around a little bit, it seems that the flag `/ZI` for [Debug Information Format](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019) is the one causing problem. By default in Visual Studio console application project, it is set to `Program Database for Edit And Continue (/ZI)` in `Debug` mode. However, the project that CMake generated set that flag to `None` and in `Release` mode that flag is set to `Program Database (/Zi)`, and both compiled just fine.

So I switch it to `/Zi` in `Debug` mode and it works. No more error.

[Test_Binlog.log](https://github.com/Morgan-Stanley/binlog/files/4289976/Test_Binlog.log)

**Comment by erenon** [comment] 2020-03-05 18:37
Thanks. I take this was because of an incompatible set of MSVC flags, and there's no Binlog change needed to get this right - so I'm closing this issue. If you think otherwise, please reopen.
Thanks for reporting!

**Comment by saberhawk** [comment] 2021-08-10 01:19
I tracked the offending `long` from the error down to this `__LINE__`.

https://github.com/morganstanley/binlog/blob/aed64ff79c323982b0172d438dcad06d0b6112a8/include/binlog/create_source_and_event.hpp#L50

Surround it with a `static_cast<uint64_t>()` to fix Edit And Continue.

**Comment by erenon** [comment] 2021-08-10 07:03
Hi @saberhawk, thanks for the info. Can you tell me more about the environment that reproduces the issue? (msvc version, flags, etc.) If I'm not able to reproduce it, I'll have to fix the issue blindly.
I also find it interesting that `__LINE__` expands to a long, instead of a literal. Is that correct?

**Comment by saberhawk** [comment] 2021-08-10 17:21
My compiler version is `19.28.29914` but the error only occurs when Debug Information Format is set to `Program Database for Edit And Continue (/ZI)`.

This snippet logs `type is long`.

```cpp
BINLOG_INFO("type is {}", typeid(__LINE__).name());
```

**Comment by erenon** [comment] 2021-08-11 10:36
Thanks, reproduced.

**Closed** 2021-08-11 10:52 UTC
